export const PER_PAGE_SET = 'PER_PAGE_SET';
export const PER_PAGE_RESET = 'PER_PAGE_RESET';

export const OCCURRED_BEFORE_SET = 'OCCURRED_BEFORE_SET';
export const OCCURRED_BEFORE_CLEAR = 'OCCURRED_BEFORE_CLEAR';

export const OCCURRED_AFTER_SET = 'OCCURRED_AFTER_SET';
export const OCCURRED_AFTER_CLEAR = 'OCCURRED_AFTER_CLEAR';

export const QUERY_SET = 'QUERY_SET';
export const QUERY_CLEAR = 'QUERY_CLEAR';

export const PROXIMITY_SET = 'PROXIMITY_SET';
export const PROXIMITY_CLEAR = 'PROXIMITY_CLEAR';

export const LOADING_START_LOADING = 'LOADING_START_LOADING';
export const LOADING_STOP_LOADING = 'LOADING_STOP_LOADING';

export const INCIDENTS_LOADING_START = 'INCIDENTS_LOADING_START';
export const INCIDENTS_LOADING_STOP = 'INCIDENTS_LOADING_STOP';
export const INCIDENTS_FETCH_FAIL = 'INCIDENTS_FETCH_FAIL';

export const LAST_PAGE_FETCH_NUMBER_SET = 'LAST_PAGE_FETCH_NUMBER_SET';
export const LAST_PAGE_FETCH_NUMBER_RESET = 'LAST_PAGE_FETCH_NUMBER_RESET';
export const LAST_PAGE_FETCH_NUMBER_INCREMENT = 'LAST_PAGE_FETCH_NUMBER_INCREMENT';

export const INCIDENTS_ADD_BATCH = 'INCIDENTS_ADD_BATCH';
export const INCIDENTS_CLEAR = 'INCIDENTS_CLEAR';

export const INCIDENT_SET = 'INCIDENT_SET';
export const INCIDENT_CLEAR = 'INCIDENT_CLEAR';

export const INCIDENT_LOADING_START = 'INCIDENT_LOADING_START';
export const INCIDENT_LOADING_STOPT = 'INCIDENT_LOADING_STOPT';
export const INCIDENT_FETCH_FAILED = 'INCIDENT_FETCH_FAILED';

export const CURRENT_PAGE_SET = 'CURRENT_PAGE_SET';
export const CURRENT_PAGE_RESET = 'CURRENT_PAGE_RESET';

export const LOCATIONS_ADD_BATCH = 'LOCATIONS_ADD_BATCH';
export const LOCATIONS_SET_BATCH = 'LOCATIONS_SET_BATCH';
export const LOCATIONS_CLEAR = 'LOCATIONS_CLEAR';

export const LOADING_LOCATIONS_START = 'LOADING_LOCATIONS_START';
export const LOADING_LOCATIONS_STOP = 'LOADING_LOCATIONS_STOP';
