export const PER_PAGE_SET = 'PER_PAGE_SET';
export const PER_PAGE_RESET = 'PER_PAGE_RESET';

export const OCCURRED_BEFORE_SET = 'OCCURRED_BEFORE_SET';
export const OCCURRED_BEFORE_CLEAR = 'OCCURRED_BEFORE_CLEAR';
